import { Platform, StyleSheet } from "react-native";

import { Spacing } from "@/constants/spacing";
import { Typography } from "@/constants/typography";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, paddingTop: Platform.OS === "android" ? 44 : 0 },
  container: {
    paddingHorizontal: 16,
    paddingTop: 16,
    gap: 16,
    paddingBottom: 110,
  },
  header: { gap: 4 },
  kicker: {
    fontSize: Typography.sizes.xs,
    letterSpacing: 2,
    fontWeight: "700",
  },
  title: {
    fontSize: Typography.sizes.display,
    fontWeight: "700",
    lineHeight: 38,
  },

  // Horizontal week strip
  weekStripContainer: {
    paddingVertical: 4,
    marginHorizontal: -16,
  },
  weekScrollContent: {
    paddingHorizontal: 16,
    gap: 12,
  },
  weekDayCell: {
    width: 50,
    height: 78,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    gap: 5,
    position: "relative",
  },
  weekDayNameText: {
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  weekDayNumText: { fontSize: 16, fontWeight: "800" },
  activeDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    position: "absolute",
    bottom: 8,
  },

  // Premium Layout Styles
  premiumHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
  },
  premiumHeaderTitle: {
    fontSize: 16,
    fontWeight: "700",
  },
  avatarMini: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
  },
  dateBannerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginVertical: 4,
  },
  largeDateText: {
    fontSize: 28,
    fontWeight: "800",
  },
  taskCountSubtitle: {
    fontSize: 13,
    fontWeight: "600",
  },
  folderCalButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#18181b",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  teamAvatars: {
    flexDirection: "row",
    alignItems: "center",
  },
  teamAvatarCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
  },
  teamAvatarText: {
    fontSize: 9,
    fontWeight: "800",
    color: "#ffffff",
  },

  // Vertical time agenda
  agendaCard: { padding: Spacing.lg, gap: 16, overflow: "hidden" },
  agendaTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "baseline",
  },
  agendaHeading: { fontSize: Typography.sizes.lg, fontWeight: "700" },
  taskCountKicker: { fontSize: Typography.sizes.xs, fontWeight: "600" },
  timelineWrapper: { gap: 12, marginTop: 4 },
  timelineRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  timeColumn: { width: 68, paddingTop: 14 },
  timeLabelText: { fontSize: 11, fontWeight: "700" },
  timelineConnector: { width: 12, alignItems: "center", alignSelf: "stretch" },
  timelineNode: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginTop: 16,
    zIndex: 1,
  },
  timelineLine: {
    width: 1.5,
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    position: "absolute",
    top: 24,
    bottom: -12,
  },
  timelineItemCard: { flex: 1, padding: Spacing.md, gap: 4, borderWidth: 1 },
  timelineTaskTitle: { fontSize: 13, fontWeight: "600" },
  timelineMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 2,
  },
  timelineMetaText: { fontSize: 9, fontWeight: "600" },

  // Collapsible heatmap card
  collapsibleHeatmapCard: { padding: Spacing.md, gap: 8 },
  collapsibleHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
  },
  collapsibleTitleLeft: { flexDirection: "row", alignItems: "center", gap: 8 },
  collapsibleTitleText: { fontSize: 14, fontWeight: "700" },
  heatmapContent: {
    gap: 12,
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.05)",
    paddingTop: 12,
  },

  // Custom Calendar Styles
  customCalendarHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  monthLabel: { fontSize: 16, fontWeight: "700" },
  navArrows: { flexDirection: "row", gap: 4 },
  arrowBtn: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    backgroundColor: "rgba(255, 255, 255, 0.02)",
  },
  weekdaysHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.05)",
    paddingBottom: 8,
  },
  weekdayLabel: {
    width: "14.28%",
    textAlign: "center",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    rowGap: 8,
  },
  dayCellPlaceholder: {
    width: "14.28%",
    aspectRatio: 1,
  },
  dayCellContainer: {
    width: "14.28%",
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
  },
  dayBadgeCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.04)",
  },
  dayNumText: { fontSize: 13 },
  legendWrapperInside: {
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  legendRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  legendSwatch: { width: 12, height: 12, borderRadius: 3 },
  legendText: { fontSize: Typography.sizes.xs, fontWeight: "600" },

  summaryRow: { flexDirection: "row", gap: 12 },
  summaryHalf: { flex: 1, gap: 4, padding: Spacing.md },
  statHeader: { flexDirection: "row", alignItems: "center", gap: 6 },
  summaryLabel: { fontSize: Typography.sizes.xs, fontWeight: "600" },
  summaryValue: { fontSize: 22, fontWeight: "700" },
  detailCard: { padding: Spacing.lg, gap: 12 },
  detailHeader: { flexDirection: "row", alignItems: "center", gap: 8 },
  detailTitle: { fontSize: Typography.sizes.lg, fontWeight: "700" },
  detailBody: { gap: 12 },
  scoreHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
  },
  scoreBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  scoreBadgeText: {
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  progressRingsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingVertical: 12,
  },
  ringCardContainer: {
    flex: 1,
    alignItems: "center",
    gap: 8,
  },
  ringCardTitle: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  ringGraphicWrap: {
    alignItems: "center",
    justifyContent: "center",
  },
  ringCardStat: {
    fontSize: 11,
    fontWeight: "600",
  },
  ringDivider: {
    width: 1,
    height: 60,
    opacity: 0.15,
  },
  detailStatLabel: { fontSize: Typography.sizes.xs, fontWeight: "700", letterSpacing: 0.8 },
  detailStatVal: { fontSize: Typography.sizes.md, fontWeight: "700" },
  divider: {
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    marginVertical: 4,
  },
  listsContainer: { flexDirection: "row", gap: 16 },
  listSection: { flex: 1, gap: 6 },
  sectionLabel: { fontSize: Typography.sizes.sm, fontWeight: "700" },
  detailListItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  listItemText: { fontSize: Typography.sizes.xs, fontWeight: "500" },
  noItemsText: { fontSize: Typography.sizes.xs, fontStyle: "italic" },
  noHistoryWrap: {
    flexDirection: "column",
    alignItems: "center",
    gap: 12,
    paddingVertical: 16,
  },
  noHistoryText: {
    fontSize: Typography.sizes.sm,
    textAlign: "center",
    marginTop: 4,
  },
  emptyAgendaContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 32,
    gap: 8,
  },
  emptyAgendaText: {
    fontSize: 14,
    fontWeight: "700",
    marginTop: 4,
  },
  emptyAgendaSubtext: {
    fontSize: 11,
    textAlign: "center",
    opacity: 0.8,
    paddingHorizontal: 16,
    lineHeight: 16,
  },
});
