import { Platform, StyleSheet } from "react-native";

import { Spacing } from "@/constants/spacing";
import { Typography } from "@/constants/typography";

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  safeArea: { flex: 1, paddingTop: Platform.OS === "android" ? 44 : 0 },
  container: { flex: 1, paddingHorizontal: 16, paddingTop: 16, gap: 16 },
  header: { gap: 4 },
  kicker: {
    fontSize: Typography.sizes.xs,
    letterSpacing: 2,
    fontWeight: "700",
  },
  title: {
    fontSize: Typography.sizes.display,
    fontWeight: "700",
    lineHeight: 38,
  },
  warningBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: Spacing.md,
    borderRadius: 16,
    borderWidth: 1,
  },
  warningText: { fontSize: Typography.sizes.sm, fontWeight: "600" },
  successBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: Spacing.md,
    borderRadius: 16,
    borderWidth: 1,
  },
  successText: { fontSize: Typography.sizes.sm, fontWeight: "600" },
  summaryRow: { flexDirection: "row", gap: 12 },
  summaryHalf: { flex: 1, gap: 4, padding: Spacing.md },
  summaryLabel: { fontSize: Typography.sizes.xs, fontWeight: "600" },
  summaryVal: { fontSize: 22, fontWeight: "800" },
  progressSection: { padding: Spacing.lg, gap: Spacing.sm },
  progressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  progressTitle: { fontSize: Typography.sizes.md, fontWeight: "700" },
  progressPercent: { fontSize: Typography.sizes.md, fontWeight: "800" },
  addCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 6,
    paddingLeft: 14,
  },
  addInput: { flex: 1, fontSize: Typography.sizes.md, paddingVertical: 10 },
  addButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  listContent: { gap: 10, paddingBottom: 120 },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderStyle: "dashed",
    borderRadius: 24,
    padding: 32,
    gap: 12,
    marginTop: 20,
  },
  emptyTitle: { fontSize: Typography.sizes.lg, fontWeight: "700" },
  emptySubtitle: { fontSize: Typography.sizes.sm, textAlign: "center" },
  habitWrap: { gap: 8 },
  habitCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: Spacing.md,
  },
  habitLeft: { flexDirection: "row", alignItems: "center", gap: 12, flex: 1 },
  habitTexts: { flex: 1, gap: 4 },
  habitTitleText: { fontSize: Typography.sizes.md, fontWeight: "600" },
  metaRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  metaText: { fontSize: Typography.sizes.xs, fontWeight: "500" },
  weeklyGrid: { flexDirection: "row", gap: 6, marginTop: 4 },
  gridDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  gridText: { fontSize: 8, fontWeight: "800" },
  actions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingLeft: 10,
  },
  alarmDropdown: {
    padding: Spacing.md,
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.05)",
  },
  quickOptions: { gap: 8, paddingVertical: 4 },
  quickBtn: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10 },
  dropdownBottom: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 4,
  },
  customToggleBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  clearBtn: { padding: 8 },
  customPicker: {
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.05)",
    paddingTop: 12,
  },
  timeRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  timeField: {
    width: 56,
    borderWidth: 1,
    borderRadius: 10,
    padding: 6,
    textAlign: "center",
  },
  daysRow: { flexDirection: "row", justifyContent: "space-between", gap: 4 },
  dayBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  setBtn: { paddingVertical: 10, borderRadius: 12, alignItems: "center" },
  prioritySelectorRow: {
    gap: 8,
    marginTop: 10,
    marginBottom: 4,
  },
  prioritySelectorLabel: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  priorityChoicePill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  tagBadge: {
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    alignSelf: "flex-start",
  },
  tagBadgeText: {
    fontSize: 9,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  timeSelectWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 12,
  },
  timeCol: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    minWidth: 70,
  },
  chevronBtn: {
    padding: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  timeText: {
    fontSize: 28,
    fontWeight: "700",
    marginVertical: 2,
    fontVariant: ["tabular-nums"],
  },
  presetOffsetsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
    marginVertical: 8,
  },
  offsetBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  offsetBtnText: {
    fontSize: 12,
    fontWeight: "600",
  },
});
