import { Platform, StyleSheet } from "react-native";
import { Spacing } from "@/constants/spacing";
import { Typography } from "@/constants/typography";

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  safeArea: { flex: 1, paddingTop: Platform.OS === "android" ? 44 : 0 },
  container: { flex: 1, paddingHorizontal: 16, paddingTop: 16, gap: 14 },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  kicker: { fontSize: Typography.sizes.xs, fontWeight: "700", letterSpacing: 2 },
  title: { fontSize: Typography.sizes.display, fontWeight: "700", lineHeight: 38 },
  clearBtn: { paddingVertical: 6 },
  listManager: { gap: 12 },
  listHeaderRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  sectionTitle: { fontSize: Typography.sizes.md, fontWeight: "700" },
  listPills: { gap: 8, paddingVertical: 4 },
  listPill: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, borderWidth: 1 },
  createListRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 14,
    paddingLeft: 12,
    paddingRight: 6,
    paddingVertical: 6,
  },
  createListInput: { flex: 1, fontSize: Typography.sizes.sm },
  smallAddBtn: { width: 32, height: 32, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  addTaskCard: { flexDirection: "row", alignItems: "center", padding: 3, paddingLeft: 10 },
  addTaskInput: { flex: 1, fontSize: 13, paddingVertical: 6 },
  addBtn: { width: 34, height: 34, borderRadius: 10, alignItems: "center", justifyContent: "center" },
  
  categoryChoiceRow: { gap: 6, marginTop: 6, marginBottom: 2 },
  categoryChoiceLabel: { fontSize: 10, fontWeight: "700", letterSpacing: 0.8, textTransform: "uppercase" },
  categoryChoicePills: { gap: 6, paddingRight: 4 },
  categoryChoicePill: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 5 },
  
  listContent: { gap: 8, paddingBottom: 120 },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderStyle: "dashed",
    borderRadius: 24,
    padding: 32,
    gap: 12,
    marginTop: 20,
  },
  emptyTitle: { fontSize: Typography.sizes.lg, fontWeight: "700" },
  emptySubtitle: { fontSize: Typography.sizes.sm, textAlign: "center" },
  
  // Category Filter Row (Pills at the top of tasks)
  categoryFilterContainer: {
    paddingVertical: 2,
    marginBottom: 2,
  },
  categoryFilterScroll: {
    gap: 6,
  },
  categoryFilterPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: 1,
  },
  categoryFilterPillText: {
    fontSize: 11,
    fontWeight: "700",
  },

  // Horizontal week strip
  weekStripContainer: {
    paddingVertical: 2,
    marginHorizontal: -16,
    marginBottom: 2,
  },
  weekScrollContent: {
    paddingHorizontal: 16,
    gap: 8,
  },
  weekDayCell: {
    width: 40,
    height: 52,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    gap: 3,
    position: "relative",
  },
  weekDayNameText: {
    fontSize: 8,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  weekDayNumText: { fontSize: 12, fontWeight: "800" },
  activeDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    marginTop: 1,
  },

  // Todo items structure
  todoItemCard: { padding: Spacing.md, flexDirection: "column", gap: 8 },
  todoLeft: { flex: 1, flexDirection: "row", alignItems: "center", gap: 12 },
  todoTexts: { flex: 1, gap: 2 },
  todoTitle: { fontSize: Typography.sizes.md, fontWeight: "600" },
  reminderRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  reminderText: { fontSize: Typography.sizes.xs, fontWeight: "600" },
  actions: { flexDirection: "row", alignItems: "center", gap: 14, paddingLeft: 10 },
  
  // Centered Alarm Modal Overlay
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.65)",
  },
  centeredAlarmCard: {
    width: "90%",
    padding: 20,
    gap: 16,
    borderRadius: 24,
    borderWidth: 1,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.5,
    shadowRadius: 24,
    elevation: 20,
  },
  modalHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitleText: {
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: -0.3,
  },
  modalSubtitleText: {
    fontSize: 12,
    lineHeight: 18,
  },
  alarmOptionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginVertical: 4,
  },
  premiumAlarmBtn: {
    flex: 1,
    minWidth: "28%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.04)",
  },
  customToggleBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 6,
  },

  todoMainRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  alarmModal: {
    padding: Spacing.md,
    marginTop: 8,
    gap: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  alarmOptions: {
    flexDirection: "row",
    gap: 8,
    paddingVertical: 4,
  },
  alarmBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  metaRow: { flexDirection: "row", alignItems: "center", gap: 12, marginTop: 2, flexWrap: "wrap" },
  expandSection: { borderTopWidth: 1, paddingTop: 10, marginTop: 4, gap: 10 },
  sectionContainer: { marginBottom: 6, gap: 4 },
  sectionHeaderPressable: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 4, paddingHorizontal: 4 },
  sectionHeaderText: { fontSize: 11, fontWeight: "700", textTransform: "uppercase", letterSpacing: 1.2 },
  sectionTasksList: { gap: 6 },
  tagBadge: { borderWidth: 1, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8, alignSelf: "flex-start" },
  tagBadgeText: { fontSize: 9, fontWeight: "700", textTransform: "uppercase" },
  
  segmentedControlContainer: {
    flexDirection: "row",
    padding: 4,
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.05)",
  },
  segmentButton: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", paddingVertical: 10, borderRadius: 12, borderWidth: 1, borderColor: "transparent", gap: 6 },
  segmentText: { fontSize: 13 },
  
  editTaskRow: { flexDirection: "row", alignItems: "center", gap: 10, marginVertical: 2 },
  editLabel: { fontSize: 12, fontWeight: "600", width: 54 },
  editTitleInput: { flex: 1, borderWidth: 1, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6, fontSize: 13 },
  migrateCategoryRow: { flexDirection: "row", alignItems: "center", gap: 10, marginVertical: 2 },
  migratePills: { gap: 6, paddingVertical: 2 },
  migratePill: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 10, borderWidth: 1 },
  dividerSmall: { height: 1, backgroundColor: "rgba(255, 255, 255, 0.05)", marginVertical: 4 },
  expandedActionsRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 10, width: "100%" },
  expandedActionBtn: { flexDirection: "row", alignItems: "center", gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10 },
  expandedActionBtnText: { fontSize: 12, fontWeight: "700" },
  warningBanner: { flexDirection: "row", alignItems: "center", gap: 8, padding: Spacing.md, borderRadius: 16, borderWidth: 1 },
  warningText: { fontSize: Typography.sizes.sm, fontWeight: "600" },
  successBanner: { flexDirection: "row", alignItems: "center", gap: 8, padding: Spacing.md, borderRadius: 16, borderWidth: 1 },
  successText: { fontSize: Typography.sizes.sm, fontWeight: "600" },
  summaryRow: { flexDirection: "row", gap: 12 },
  summaryHalf: { flex: 1, gap: 4, padding: Spacing.md },
  summaryLabel: { fontSize: Typography.sizes.xs, fontWeight: "600" },
  summaryVal: { fontSize: 22, fontWeight: "800" },
  progressSection: { padding: Spacing.lg, gap: Spacing.sm },
  progressHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  progressTitle: { fontSize: Typography.sizes.md, fontWeight: "700" },
  progressPercent: { fontSize: Typography.sizes.md, fontWeight: "800" },
  habitWrap: { gap: 8 },
  weeklyGrid: { flexDirection: "row", gap: 6, marginTop: 4 },
  gridDot: { width: 22, height: 22, borderRadius: 11, borderWidth: 1, alignItems: "center", justifyContent: "center" },
  gridText: { fontSize: 8, fontWeight: "800" },
  dropdownBottom: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 4 },
  timeSelectWrap: { flexDirection: "row", alignItems: "center", justifyContent: "center", marginVertical: 12 },
  timeCol: { alignItems: "center", justifyContent: "center", backgroundColor: "rgba(255, 255, 255, 0.03)", borderRadius: 16, paddingHorizontal: 12, paddingVertical: 6, borderWidth: 1, borderColor: "rgba(255, 255, 255, 0.08)", minWidth: 70 },
  chevronBtn: { padding: 8, alignItems: "center", justifyContent: "center" },
  timeText: { fontSize: 28, fontWeight: "700", marginVertical: 2, fontVariant: ["tabular-nums"] },
  presetOffsetsRow: { flexDirection: "row", justifyContent: "space-between", gap: 8, marginVertical: 8 },
  offsetBtn: { flex: 1, paddingVertical: 8, borderRadius: 10, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "rgba(255, 255, 255, 0.05)" },
  offsetBtnText: { fontSize: 12, fontWeight: "600" },
});
