import AsyncStorage from "@react-native-async-storage/async-storage";
import {
  earnPebble,
  undoLastPebble,
  getPebbleCounts,
  getGemsBalance,
  earnBonusGem,
  spendGems,
  getMainStreakRecoveryInfo,
  recoverMainStreak,
  PEBBLE_LOG_KEY,
} from "../pebbleService";

let mockStore: Record<string, string> = {};

jest.mock("@react-native-async-storage/async-storage", () => {
  return {
    getItem: jest.fn().mockImplementation(async (key) => mockStore[key] || null),
    setItem: jest.fn().mockImplementation(async (key, value) => {
      mockStore[key] = String(value);
      return null;
    }),
    removeItem: jest.fn().mockImplementation(async (key) => {
      delete mockStore[key];
      return null;
    }),
    clear: jest.fn().mockImplementation(async () => {
      mockStore = {};
      return null;
    }),
  };
});

jest.mock("../stateEvents", () => {
  return {
    emitStateChange: jest.fn(),
  };
});

describe("pebbleService & gems tests", () => {
  beforeEach(() => {
    mockStore = {};
    jest.clearAllMocks();
  });

  it("should start with zero Gems balance and empty pebble counts", async () => {
    const balance = await getGemsBalance();
    expect(balance).toBe(0);

    const counts = await getPebbleCounts();
    expect(counts.lifetime).toBe(0);
    expect(counts.monthly).toBe(0);
  });

  it("should earn a pebble, award a daily consistency gem, and calculate balance", async () => {
    const success = await earnPebble("task");
    expect(success).toBe(true);
    
    // First pebble of the day should award 1 Gem
    const balance = await getGemsBalance();
    expect(balance).toBe(1);

    const counts = await getPebbleCounts();
    expect(counts.lifetime).toBe(1);
  });

  it("should enforce the daily limit of 15 pebbles", async () => {
    // Earn 15 pebbles today
    for (let i = 0; i < 15; i++) {
      const success = await earnPebble("task");
      expect(success).toBe(true);
    }

    // Try to earn a 16th pebble
    const success = await earnPebble("task");
    expect(success).toBe(false);

    const counts = await getPebbleCounts();
    expect(counts.lifetime).toBe(15);
  });

  it("should convert pebbles to gems at a rate of 45 pebbles = 1 gem", async () => {
    // Backfill logs directly since daily limit is 15
    const log = [];
    const now = Date.now();
    // 90 pebbles spread across the last 10 days to bypass daily cap
    for (let day = 0; day < 10; day++) {
      const timestamp = now - day * 24 * 60 * 60 * 1000;
      for (let p = 0; p < 9; p++) {
        log.push({ type: "task", timestamp });
      }
    }
    await AsyncStorage.setItem(PEBBLE_LOG_KEY, JSON.stringify(log));

    // 90 pebbles = 2 gems from conversion.
    // Plus, mockStore does not have daily bonus entries unless generated by earnPebble.
    // So getGemsBalance should yield at least 2 gems.
    const balance = await getGemsBalance();
    expect(balance).toBe(2);
  });

  it("should support manual bonus gems and spending gems", async () => {
    await earnBonusGem(5);
    let balance = await getGemsBalance();
    expect(balance).toBe(5);

    const spentSuccess = await spendGems(2);
    expect(spentSuccess).toBe(true);

    balance = await getGemsBalance();
    expect(balance).toBe(3);

    const spentFail = await spendGems(10);
    expect(spentFail).toBe(false);
    expect(balance).toBe(3);
  });

  it("should detect broken main streak and recover it", async () => {
    const now = Date.now();
    const dayMs = 24 * 60 * 60 * 1000;

    // Create a 5-day streak ending 2 days ago (mocking a missed yesterday)
    const log = [];
    for (let i = 2; i < 7; i++) {
      log.push({ type: "task", timestamp: now - i * dayMs });
    }
    await AsyncStorage.setItem(PEBBLE_LOG_KEY, JSON.stringify(log));

    // Yesterday is missed. Today is open.
    // Check if recovery is eligible
    const recoveryInfo = await getMainStreakRecoveryInfo();
    expect(recoveryInfo.eligible).toBe(true);
    expect(recoveryInfo.previousStreak).toBe(5);

    // Give some gems to spend
    await earnBonusGem(1);

    // Recover streak
    const recoverSuccess = await recoverMainStreak();
    expect(recoverSuccess).toBe(true);

    // Yesterday should now have a pebble, making yesterday completed
    const recoveryInfoAfter = await getMainStreakRecoveryInfo();
    expect(recoveryInfoAfter.eligible).toBe(false); // No longer eligible as it's healed!
  });

  it("should calculate bestStreak correctly in getPebbleCounts", async () => {
    const now = Date.now();
    const dayMs = 24 * 60 * 60 * 1000;
    
    // Create logs for days: 10 days ago to 8 days ago (3 days streak)
    // then gap
    // then 5 days ago to 2 days ago (4 days streak)
    const log = [];
    // 3 day streak
    log.push({ type: "task", timestamp: now - 10 * dayMs });
    log.push({ type: "task", timestamp: now - 9 * dayMs });
    log.push({ type: "task", timestamp: now - 8 * dayMs });
    
    // 4 day streak
    log.push({ type: "habit", timestamp: now - 5 * dayMs });
    log.push({ type: "habit", timestamp: now - 4 * dayMs });
    log.push({ type: "habit", timestamp: now - 3 * dayMs });
    log.push({ type: "habit", timestamp: now - 2 * dayMs });
    
    await AsyncStorage.setItem(PEBBLE_LOG_KEY, JSON.stringify(log));
    
    const counts = await getPebbleCounts();
    expect(counts.bestStreak).toBe(4);
  });
});

